# Generated by Django 4.0.3 on 2023-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeinventory',
            name='image',
            field=models.URLField(),
        ),
    ]
